[package]
name = "younix"
edition = "2024"
version.workspace = true

[dependencies]
clap.workspace = true
cat = { path = "../crates/cat" }
ls = { path = "../crates/ls" }
grep = { path = "../crates/grep" }
sort = { path = "../crates/sort" }
view = { path = "../crates/view" }
wc = { path = "../crates/wc" }
