[package]
name = "younix"
edition = "2024"
description.workspace = true
repository.workspace = true
version.workspace = true
license.workspace = true
readme.workspace = true
categories.workspace = true
keywords.workspace = true
exclude.workspace = true

[dependencies]
clap.workspace = true
cat = { path = "../crates/cat" }
ls = { path = "../crates/ls" }
grep = { path = "../crates/grep" }
sort = { path = "../crates/sort" }
view = { path = "../crates/view" }
wc = { path = "../crates/wc" }
