[package]
name = "ycat"
edition.workspace = true
description = "The cat command of the Younix application"
repository.workspace = true
version.workspace = true
license.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
tempfile.workspace = true
