[package]
name = "yls"
edition.workspace = true
description = "The ls command of the Younix application"
repository.workspace = true
version.workspace = true
license.workspace = true
categories = ["command-line-utilities"]
keywords.workspace = true

[dependencies]
tempfile.workspace = true
